HW12
OlgaResh1/OtusGoHomeWork pull request #15
Opened 2024-06-04 10:21 UTC by OlgaResh1

## Домашнее задание №12 «Заготовка сервиса Календарь»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Понятность и чистота кода (включая факт, что проект разбит
на пакеты по определенной логике) - до 2 баллов
- [ ] Реализовано конфигурирование сервиса - 1 балл
- [ ] Используется логгер и он настраивается из конфига - 1 балл
- [ ] Запускается простой HTTP-сервер, мидлвара удовлетворяет ТЗ - 1 балл
- [ ] Присутствуют юнит-тесты - 1 балл

Реализовано хранилище:
- [ ] in-memory - 1 балл
- [ ] sql + миграции - 2 балла

#### Зачёт от 7 баллов

2024-06-05 03:20 UTC, dshemin approved these changes

2024-06-05 03:20 UTC, dshemin commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +func (l Logger) LogHTTPRequest(r *http.Request, d time.Duration, statusCode int) {
Важно:

Класс логера не должен знать о том где и как мы его используем. В данном случае мы его крепко связали с http сервером. Этого тут быть не должно.

2024-06-05 03:20 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/middleware.go
> +		s.logger.LogHTTPRequest(r, duration, 200)
Критично:

У нас не всегда будет 200 статус код!

2024-06-05 03:20 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +		return storage.NotValidId, storage.ErrNotValidEvent
Важно:

Есть соглашение, что в случае возникновения ошибки, проверять другие возвращаемые значения нет смысла. Поэтом просто верните 0.

2024-06-05 03:20 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +func (s *Storage) Connect(ctx context.Context) (err error) {
Важно:

Получается не очень удачный интерфейс, я могу вызвать New, но получу не готовый объект для работы, мне надо ещё сделать Connect. Учитывая что без обоих вызовов мне не обойтись имеет смысл объеденить эти два метода.

2024-06-05 03:20 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	query := `select id	from events where owner_id=$1 and begin_datetime ='$2'`
Важно:

Эти два действия надо делать в транзакции, иначе другой параллельный запрос может успеть сделать вставку.

2024-06-05 03:20 UTC, dshemin commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if rowsCount != 1 {
Важно:

Думаю пользователю будет всё равно если он пытается удалить уже не существующее событие, он хочет чтобы его не было. Не стоит делать эту проверку.

2024-06-05 03:20 UTC, dshemin requested changes
Есть критичное замечание.

2024-06-09 10:32 UTC, OlgaResh1 commented on hw12_13_14_15_calendar/internal/logger/logger.go
> +func (l Logger) LogHTTPRequest(r *http.Request, d time.Duration, statusCode int) {
Поправила, логгер оставила универсальным. эту функцию перенесла в middleware

2024-06-09 10:33 UTC, OlgaResh1 commented on hw12_13_14_15_calendar/internal/server/http/middleware.go
> +		s.logger.LogHTTPRequest(r, duration, 200)
Тут простого способа вычитать статус не нашла. 
Только сделать обертку над ResponseWriter

2024-06-09 10:33 UTC, OlgaResh1 commented on hw12_13_14_15_calendar/internal/storage/memory/storage.go
> +		return storage.NotValidId, storage.ErrNotValidEvent
ок, поправила

2024-06-09 10:34 UTC, OlgaResh1 commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +func (s *Storage) Connect(ctx context.Context) (err error) {
Объединила New и Connect для обоих Storage

2024-06-09 10:34 UTC, OlgaResh1 commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	query := `select id	from events where owner_id=$1 and begin_datetime ='$2'`
Да, согласна, сделала тут транзакцию

2024-06-09 10:35 UTC, OlgaResh1 commented on hw12_13_14_15_calendar/internal/storage/sql/storage.go
> +	if rowsCount != 1 {
убрала

2024-06-20 20:05 UTC, merged